spring:
  application:
    name: kafka-lesson-consumer

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db # URL ??
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update

server:
  port: 8081